### ISSUE TITLE
Feature Request: Custom Metrics Collection and Registration

### ISSUE THREAD

**Issue by laplaque** [laplaque/instana_plugins#20]
## Overview

Extend the Instana plugins architecture to support custom metrics collection beyond the default process monitoring metrics, with TOML-based configuration and multiple OpenTelemetry metric types.

## Current Limitations

**Fixed Metric Set**: All services currently collect the same predefined process metrics:
- CPU/memory usage, process count, disk I/O, file descriptors, thread counts, context switches

**Single Metric Type**: All metrics are implemented as OpenTelemetry Observable Gauges, regardless of their semantic meaning

**No Extensibility**: Services cannot register application-specific or business metrics

**No Configuration**: The `metric_types` field in `plugin.toml` is not actively used for customization

### 1. TOML-Based Custom Metrics Configuration

Extend `plugin.toml` to support custom metric definitions:

```toml
[custom_metrics]
enabled = true

[[custom_metrics.sources]]
name = "jmx_collector"
type = "jmx"
endpoint = "localhost:9999"
metrics = [
    {name = "heap_memory", otel_type = "gauge", unit = "bytes"},
    {name = "thread_pool_size", otel_type = "updowncounter", unit = "1"}
]

[[custom_metrics.sources]]
name = "log_parser"
type = "log_file" 
path = "/var/log/app.log"
metrics = [
    {name = "error_count", otel_type = "counter", pattern = "ERROR"},
    {name = "response_time", otel_type = "histogram", pattern = "Transaction.*completed in (\\d+)ms", buckets = [10, 50, 100, 500, 1000]}
]

[[custom_metrics.sources]]
name = "http_endpoint"
type = "http"
url = "http://localhost:8080/metrics"
format = "json"
interval = 30
metrics = [
    {name = "active_sessions", otel_type = "gauge", json_path = "$.sessions.active"},
    {name = "requests_per_second", otel_type = "counter", json_path = "$.requests.total"}
]
```

### 2. Multiple OpenTelemetry Metric Types

Support all OpenTelemetry metric instruments:

**Counter** (monotonically increasing):
```python
counter = self.meter.create_counter("requests_total")
counter.add(1, {"method": "GET"})
```

**UpDownCounter** (can increase/decrease):
```python
updown = self.meter.create_up_down_counter("active_connections") 
updown.add(1)  # connection opened
```

**Histogram** (distributions/latencies):
```python
histogram = self.meter.create_histogram("request_duration_ms")
histogram.record(125.3, {"endpoint": "/api/users"})
```

**Observable Gauge** (current implementation):
```python
gauge = self.meter.create_observable_gauge("cpu_usage")
```

### 3. Pluggable Metric Source System

**Built-in Source Types**:
- `jmx`: Java Management Extensions
- `log_file`: Log file parsing with regex patterns
- `http`: HTTP/REST endpoint polling
- `database`: SQL query execution
- `file`: File-based metrics (JSON, CSV, etc.)
- `command`: Execute shell commands

**Custom Source Plugins**: Allow third-party metric collectors

### 4. Architecture Changes Required

**New Components**:
- `MetricSourceRegistry`: Manage metric source plugins
- `CustomMetricCollector`: Orchestrate custom metric collection
- `MetricSourceBase`: Abstract base class for metric sources
- `ConfigValidator`: Validate TOML metric configurations

**Modified Components**:
- `base_sensor.py`: Integrate custom metrics into monitoring loop
- `otel_connector.py`: Support multiple OpenTelemetry metric types
- `toml_utils.py`: Parse and validate custom metrics configuration
- `metadata_store.py`: Store custom metric metadata

### 5. Implementation Phases

**Phase 1: Core Infrastructure**
- Metric source plugin system
- TOML configuration parsing
- Multiple OTel metric type support

**Phase 2: Basic Source Types**
- HTTP endpoint polling
- Log file parsing
- Command execution

**Phase 3: Advanced Sources**
- JMX integration
- Database connectivity
- File-based metrics

**Phase 4: Advanced Features**
- Custom aggregation functions
- Metric transformations
- Conditional collection

## Impact Assessment

**Complexity**: Major architectural change requiring significant development and testing effort

**Backward Compatibility**: Must maintain existing functionality without breaking changes

**Performance**: Custom metric collection could impact monitoring overhead

**Dependencies**: May require additional Python packages (JMX, database drivers, etc.)

## Success Criteria

- Services can define custom metrics via TOML configuration
- Support for all OpenTelemetry metric types
- Pluggable architecture for metric sources
- Zero impact on existing services
- Comprehensive test coverage for all source types
- Performance benchmarks showing acceptable overhead

## Target Release

Proposed for v1.0.0 as a major feature release after psutil migration stabilization.

## Dependencies

- Completion of psutil migration (recently completed)
- Stable OpenTelemetry integration
- TOML configuration framework enhancements

## Related Work

This feature request emerged from discussions about extending the current process monitoring capabilities to support application-specific metrics and business KPIs that go beyond standard system metrics.

**Comment by laplaque** [comment]
## Release v0.3.00: Basic Built-in Metric Sources

### Overview
Implement fundamental metric source types for immediate value: HTTP endpoints, command execution, and log file parsing.

### Deliverables

**1. HTTP Endpoint Source** (`common/metric_sources/http_source.py`)
- Poll REST/HTTP endpoints for metrics data
- Support JSON response parsing with JSONPath expressions
- Configurable intervals, timeouts, and retry logic
- Authentication support (Bearer tokens, basic auth)
- Response validation and error handling

**2. Command Execution Source** (`common/metric_sources/command_source.py`)
- Execute shell commands and parse output for metrics
- Support for various output formats (JSON, CSV, plain text)
- Regex-based value extraction from command output
- Command timeout and error handling
- Security considerations for command execution

**3. Log File Parsing Source** (`common/metric_sources/log_source.py`)
- Monitor log files for metric-relevant patterns
- Regex-based pattern matching and value extraction
- File rotation handling and position tracking
- Rate-based metrics (errors per minute, transactions per second)
- Configurable file paths and update intervals

**4. Enhanced Configuration**
- Extended TOML configuration for new source types
- Validation for source-specific parameters
- Configuration templates and examples

**5. Comprehensive Testing**
- Unit tests for each source type
- Integration tests with mock services
- Performance and reliability testing
- Documentation and usage examples

### Configuration Example
```toml
[[custom_metrics.sources]]
name = "api_health"
type = "http"
url = "http://localhost:8080/health"
interval = 30
metrics = [
    {name = "response_time", otel_type = "histogram", json_path = "$.response_time"},
    {name = "active_connections", otel_type = "gauge", json_path = "$.connections.active"}
]

[[custom_metrics.sources]]
name = "error_monitor"
type = "log_file"
path = "/var/log/app.log"
interval = 10
metrics = [
    {name = "error_count", otel_type = "counter", pattern = "ERROR", unit = "1"}
]
```

### Success Criteria
- 3 production-ready built-in source types
- Real-world integration examples
- Performance benchmarks established
- 85%+ test coverage
- Comprehensive documentation

**Comment by laplaque** [comment]
## Release v0.4.00: Dynamic Plugin System & Advanced Features

### Overview
Implement dynamic loading capabilities, advanced metric aggregation, and enhanced configuration management for production readiness.

### Deliverables

**1. Dynamic Plugin Loader** (`common/plugin_loader.py`)
- Runtime discovery and loading of custom metric source plugins
- Plugin validation and compatibility checking
- Secure plugin sandboxing and error isolation
- Plugin lifecycle management (load/unload/reload)
- Support for both Python modules and external executables

**2. Advanced Metric Aggregation** (`common/aggregators/`)
- Time-window aggregation (sliding windows, tumbling windows)
- Statistical aggregations (percentiles, moving averages)
- Cross-metric calculations and derived metrics
- Memory-efficient aggregation algorithms
- Configurable aggregation rules via TOML

**3. Enhanced Configuration Management**
- Configuration hot-reloading without restart
- Environment variable interpolation
- Configuration inheritance and composition
- Validation with detailed error reporting
- Configuration migration utilities

**4. Database Integration Source** (`common/metric_sources/database_source.py`)
- SQL query execution for metric collection
- Support for PostgreSQL, MySQL, SQLite, SQL Server
- Connection pooling and query optimization
- Parameterized queries for security
- Query result transformation and mapping

**5. Production Features**
- Circuit breaker pattern for failing sources
- Graceful degradation and fallback mechanisms
- Comprehensive logging and debugging tools
- Performance monitoring and bottleneck detection
- Memory usage optimization

### Configuration Example
```toml
[custom_metrics]
plugin_directories = ["/opt/plugins", "./local_plugins"]
aggregation_window = "5m"

[[custom_metrics.sources]]
name = "database_metrics"
type = "database"
connection_string = "postgresql://user:pass@localhost/db"
interval = 60
queries = [
    {name = "active_users", sql = "SELECT COUNT(*) FROM users WHERE last_login > NOW() - INTERVAL '1 hour'", otel_type = "gauge"},
    {name = "transaction_volume", sql = "SELECT COUNT(*) FROM transactions WHERE created_at > $1", params = ["1h_ago"], otel_type = "counter"}
]

[[custom_metrics.aggregators]]
source = "api_health.response_time"
type = "percentile"
percentiles = [50, 95, 99]
window = "5m"
```

### Success Criteria
- Dynamic plugin system fully functional
- Production-grade reliability features
- Advanced aggregation capabilities
- 90%+ test coverage
- Performance optimizations documented
- Migration path from v0.3.00 established
