### ISSUE TITLE
v0.4.00: Dynamic Plugin System & Advanced Features

### ISSUE THREAD

**Issue by laplaque** [laplaque/instana_plugins#24]
## Epic: Custom Metrics Collection and Registration
**Epic Issue:** #20
**Depends on:** #23 (v0.3.00: Basic Built-in Metric Sources)

## Overview
Implement dynamic loading capabilities, advanced metric aggregation, and enhanced configuration management for production readiness.

## Deliverables

**1. Dynamic Plugin Loader** (`common/plugin_loader.py`)
- Runtime discovery and loading of custom metric source plugins
- Plugin validation and compatibility checking
- Secure plugin sandboxing and error isolation
- Plugin lifecycle management (load/unload/reload)
- Support for both Python modules and external executables

**2. Advanced Metric Aggregation** (`common/aggregators/`)
- Time-window aggregation (sliding windows, tumbling windows)
- Statistical aggregations (percentiles, moving averages)
- Cross-metric calculations and derived metrics
- Memory-efficient aggregation algorithms
- Configurable aggregation rules via TOML

**3. Enhanced Configuration Management**
- Configuration hot-reloading without restart
- Environment variable interpolation
- Configuration inheritance and composition
- Validation with detailed error reporting
- Configuration migration utilities

**4. Database Integration Source** (`common/metric_sources/database_source.py`)
- SQL query execution for metric collection
- Support for PostgreSQL, MySQL, SQLite, SQL Server
- Connection pooling and query optimization
- Parameterized queries for security
- Query result transformation and mapping

**5. Production Features**
- Circuit breaker pattern for failing sources
- Graceful degradation and fallback mechanisms
- Comprehensive logging and debugging tools
- Performance monitoring and bottleneck detection
- Memory usage optimization

## Configuration Example
```toml
[custom_metrics]
plugin_directories = ["/opt/plugins", "./local_plugins"]
aggregation_window = "5m"

[[custom_metrics.sources]]
name = "database_metrics"
type = "database"
connection_string = "postgresql://user:pass@localhost/db"
interval = 60
queries = [
    {name = "active_users", sql = "SELECT COUNT(*) FROM users WHERE last_login > NOW() - INTERVAL '1 hour'", otel_type = "gauge"},
    {name = "transaction_volume", sql = "SELECT COUNT(*) FROM transactions WHERE created_at > $1", params = ["1h_ago"], otel_type = "counter"}
]

[[custom_metrics.aggregators]]
source = "api_health.response_time"
type = "percentile"
percentiles = [50, 95, 99]
window = "5m"
```

## Success Criteria
- Dynamic plugin system fully functional
- Production-grade reliability features
- Advanced aggregation capabilities
- 90%+ test coverage
- Performance optimizations documented
- Migration path from v0.3.00 established

## Milestone
Target: v0.4.00
